export const getInternal = (t) => [
  {
    show_menu: true,
    show_header: true,
    id: "8OJ7c3kWgrtCUi",
    title: t("menu.services"),
    path: "services",
    pathname: "/",
  },
  {
    show_menu: true,
    show_header: true,
    id: "8Cv1Y7ZWXwl3P0",
    title: t("menu.plans"),
    path: "plans",
    pathname: "/",
  },
  {
    show_menu: true,
    show_header: true,
    id: "KbpYVi5zkFDomq",
    title: t("menu.projects"),
    path: "projects",
    pathname: "/",
  },
  {
    show_menu: true,
    show_header: true,
    id: "EQ5zNVsviYt6iD",
    title: t("menu.about"),
    path: "about",
    pathname: "/",
  },
  {
    show_menu: false,
    show_header: false,
    id: "VYt0xbhOkshtL0",
    title: t("menu.resume"),
    path: "resume",
    pathname: "/",
  },
  {
    show_menu: false,
    show_header: false,
    id: "WnLbwUlJmZ43tD",
    title: t("menu.contact"),
    path: "/contact",
  },
];

export const getExternal = (t) => [
  {
    show_menu: true,
    show_header: true,
    id: "WnLbwUlJmZ43tD",
    title: t("menu.contact"),
    path: "https://mail.google.com/mail/?fs=1&tf=cm&source=mailto&to=hello@danielvargas.dev",
  },
  {
    show_menu: true,
    show_header: true,
    id: "MvQfdtO6uRaW1f",
    title: "Ugly Cash",
    path: "https://link.ugly.cash/money_link/danielospid/50",
  },
  {
    show_menu: true,
    show_header: true,
    id: "zG7ZRyh9vjq8nz",
    title: t("menu.support"),
    path: "https://paypal.me/esdanielvargas/50",
  },
  {
    show_menu: true,
    show_header: true,
    id: "",
    title: "Curriculum Vitae",
    path: "https://drive.google.com/file/d/1T1_WN0H8QQXnC-lN9iwgmXT_3lRxGGY-/view?usp=sharing",
  },
];
