export const getPlans = (t) => [
  {
    id: "landing-plan-01",
    order: 0,
    show: true,
    path: "landing-page",
    title: t("plans.landing.title") || "Página de Aterrizaje",
    price: 350,
    caption: "Ideal para promociones, perfiles personales o validar una idea rápidamente.",
    features: [
      "1 Página (One page)",
      "Diseño 100% adaptable",
      "Formulario de contacto",
      "Configuración de dominio",
      "Enlaces a redes sociales",
      "Optimización SEO básica",
      "Carga ultrarrápida",
    ],
  },
  {
    id: "website-plan-02",
    order: 1,
    show: true,
    path: "website",
    title: "Sitio Web Profesional",
    price: 650,
    caption: "La opción perfecta para negocios que necesitan presencia corporativa sólida.",
    features: [
      "Hasta 6 páginas",
      "Diseño UI/UX premium",
      "Mapa de ubicación",
      "Galería de imágenes",
      "Optimización de velocidad",
      "SEO Técnico avanzado",
    ],
  },
  {
    id: "webapp-plan-03",
    order: 2,
    show: true,
    path: "web-app",
    title: "Aplicación Web",
    price: 1000,
    caption: "Sistemas complejos con gestión de datos y usuarios.",
    features: [
      "Autenticación de usuarios",
      "Base de datos segura",
      "Panel de administración",
      "Lógica de negocio a medida",
      "Almacenamiento de archivos",
      "Soporte prioritario"
    ],
  },
  {
    id: "custom-plan-04",
    order: 3,
    show: true,
    path: "custom",
    title: "Personalizado",
    text: "Consultar",
    caption: "¿Tienes un proyecto grande en mente? E-commerce, SAAS o plataformas educativas.",
    features: [
      "Consultoría de arquitectura",
      "Desarrollo a medida",
      "Integraciones complejas",
      "Equipo dedicado",
    ],
  },
];