export const getPlans = (t) => [
  {
    order: 0,
    show: true,
    id: "tWhz5GeSbyFRaW",
    title: t("plans.landing.title"),
    // price: 250,
    // price: 300,
    price: 350,
    description: t("plans.landing.description"),
    features: [
      t("plans.landing.features.0"),
      t("plans.landing.features.1"),
      t("plans.landing.features.2"),
      t("plans.landing.features.3"),
      t("plans.landing.features.4"),
      t("plans.landing.features.5"),
      t("plans.landing.features.6"),
      // t("plans.landing.features.7"),
      // t("plans.landing.features.8"),
      // t("plans.landing.features.9"),
      // t("plans.landing.features.10"),
    ],
    path: "landing-page",
    pathname: "/plans/",
    bg: "/images/hero.png",
  },
  {
    order: 1,
    show: true,
    id: "4NJkpQrCCtD2nh",
    title: t("plans.basic.title"),
    // price: 350,
    // price: 450,
    price: 450,
    description: t("plans.basic.description"),
    features: [
      t("plans.basic.features.0"),
      t("plans.basic.features.1"),
      t("plans.basic.features.2"),
      t("plans.basic.features.3"),
      t("plans.basic.features.4"),
      t("plans.basic.features.5"),
      t("plans.basic.features.6"),
    ],
    path: "basic-website",
    pathname: "/plans/",
    bg: "/images/hero.png",
  },
  {
    order: 2,
    show: true,
    id: "AZkAFNyB5xavVk",
    title: t("plans.standard.title"),
    // price: 450,
    price: 550,
    description: t("plans.standard.description"),
    features: [
      t("plans.standard.features.0"),
      t("plans.standard.features.1"),
      t("plans.standard.features.2"),
      t("plans.standard.features.3"),
      t("plans.standard.features.4"),
      t("plans.standard.features.5"),
      t("plans.standard.features.6"),
    ],
    path: "standard-website",
    pathname: "/plans/",
    bg: "/images/hero.png",
  },
  {
    order: 3,
    show: true,
    id: "Y8yOWx2GgMoZPA",
    title: t("plans.professional.title"),
    // price: 750,
    price: 850,
    description: t("plans.professional.description"),
    features: [
      t("plans.professional.features.0"),
      t("plans.professional.features.1"),
      t("plans.professional.features.2"),
      t("plans.professional.features.3"),
      t("plans.professional.features.4"),
      t("plans.professional.features.5"),
      t("plans.professional.features.6"),
    ],
    path: "professional-website",
    pathname: "/plans/",
    bg: "/images/hero.png",
  },
  {
    order: 4,
    show: true,
    id: "eFZCtYlvgOaz1a",
    title: t("plans.app.title"),
    price: 1000,
    description: t("plans.app.description"),
    features: [
      t("plans.app.features.0"),
      t("plans.app.features.1"),
      t("plans.app.features.2"),
      t("plans.app.features.3"),
      t("plans.app.features.4"),
      t("plans.app.features.5"),
      t("plans.app.features.6"),
    ],
    path: "application-website",
    pathname: "/plans/",
    bg: "/images/hero.png",
  },
  {
    order: 5,
    show: false,
    id: "MbFDOFvAaMuzdb",
    title: t("plans.ecommerce.title"),
    price: 1500,
    description: t("plans.ecommerce.description"),
    features: [
      t("plans.ecommerce.features.0"),
      t("plans.ecommerce.features.1"),
      t("plans.ecommerce.features.2"),
      t("plans.ecommerce.features.3"),
      t("plans.ecommerce.features.4"),
      t("plans.ecommerce.features.5"),
      t("plans.ecommerce.features.6"),
    ],
    path: "ecommerce-website",
    pathname: "/plans/",
    bg: "/images/hero.png",
  },
];
