export const getPlans = (t) => [
  {
    id: "landing-plan-01",
    order: 0,
    show: true,
    path: "landing-page",
    title: t("plans.landing.title"),
    price: 350,
    caption: t("plans.landing.caption"),
    features: [
      "1 Página (One page)",
      "Diseño 100% adaptable",
      "Formulario de contacto",
      "Configuración de dominio",
      "Enlaces a redes sociales",
      "Optimización SEO básica",
      "Carga ultrarrápida",
    ],
  },
  {
    id: "website-plan-02",
    order: 1,
    show: true,
    path: "website",
    title: t("plans.professional.title"),
    price: 850,
    caption: t("plans.professional.caption"),
    features: [
      "Hasta 6 páginas",
      "Diseño UI/UX premium",
      "Mapa de ubicación",
      "Galería de imágenes",
      "Optimización de velocidad",
      "SEO Técnico avanzado",
    ],
  },
  {
    id: "webapp-plan-03",
    order: 2,
    show: true,
    path: "web-app",
    title: t("plans.app.title"),
    price: 1050,
    caption: t("plans.app.caption"),
    features: [
      "Autenticación de usuarios",
      "Base de datos segura",
      "Panel de administración",
      "Lógica de negocio a medida",
      "Almacenamiento de archivos",
      "Soporte prioritario"
    ],
  },
  {
    id: "custom-plan-04",
    order: 3,
    show: true,
    path: "custom",
    title: t("plans.custom.title"),
    text: t("plans.custom.text"),
    caption: t("plans.custom.caption"),
    features: [
      "Consultoría de arquitectura",
      "Desarrollo a medida",
      "Integraciones complejas",
      "Equipo dedicado",
    ],
  },
];