export const getServices = (t) => [
  {
    id: "TKccyDfR5W98Oa",
    order: 0,
    show: true,
    title: t("services.web_development.title"),
    caption: t("services.web_development.caption"),
    image: "/images/development.png",
    path: "web-development",
  },
  {
    id: "CxdfH4mlQKMlp5",
    order: 1,
    show: true,
    title: t("services.web_design.title"),
    caption: t("services.web_design.caption"),
    image: "/images/design.png",
    path: "web-design",
  },
  {
    id: "fzoBWtDiWYT0Yl",
    order: 2,
    show: true,
    title: t("services.maintenance.title"),
    caption: t("services.maintenance.caption"),
    image: "/images/support.png",
    path: "maintenance",
  },
  {
    id: "J3LsF1hkQtOHtd",
    order: 3,
    show: true,
    title: t("services.google_maps.title"),
    caption: t("services.google_maps.caption"),
    image: "/images/google-maps.jpg",
    path: "google-maps",
  },
  {
    id: "2vbaE2hiyCvYEj",
    order: 4,
    show: false,
    title: t("services.professionalEmails.title"),
    caption: t("services.professionalEmails.caption"),
    image: "/images/professional-emails.png",
    path: "professional-emails",
  },
];
