export const getServices = (t) => [
  {
    id: "TKccyDfR5W98Oa",
    order: 0,
    show: true,
    title: t("services.web_development.title"),
    description: t("services.web_development.description"),
    image: "/images/development.png",
    path: "web-development",
    pathname: "/services/",
  },
  {
    id: "CxdfH4mlQKMlp5",
    order: 1,
    show: true,
    title: t("services.web_design.title"),
    description: t("services.web_design.description"),
    image: "/images/design.png",
    path: "web-design",
    pathname: "/services/",
  },
  {
    id: "fzoBWtDiWYT0Yl",
    order: 2,
    show: true,
    title: t("services.maintenance.title"),
    description: t("services.maintenance.description"),
    image: "/images/support.png",
    path: "maintenance",
    pathname: "/services/",
  },
  {
    id: "J3LsF1hkQtOHtd",
    order: 3,
    show: false,
    title: t("services.googleMaps.title"),
    description: t("services.googleMaps.description"),
    image: "/images/noisex.png",
    path: "google-maps",
    pathname: "/services/",
  },
  {
    id: "2vbaE2hiyCvYEj",
    order: 4,
    show: false,
    title: t("services.professionalEmails.title"),
    description: t("services.professionalEmails.description"),
    image: "/images/noisex.png",
    path: "professional-emails",
    pathname: "/services/",
  },
];
