export const getTools = (t) => [
  {
    icon: "🔗",
    show: true,
    id: "xDuaqcmLqZAz7q",
    title: t("tools.utm.short_title"),
    description: t("tools.utm.description"),
    path: "utm-generator",
    pathname: "/tools/",
  },
  {
    icon: "✒️",
    show: false,
    id: "FADV4vVifjC7u0",
    title: t("tools.citations.short_title"),
    description: t("tools.citations.description"),
    path: "citations",
    pathname: "/tools/",
  },
  {
    icon: "📜",
    show: false,
    id: "PqlJ8MwhRUKIWP",
    title: t("tools.references.short_title"),
    description: t("tools.references.description"),
    path: "references-generator",
    pathname: "/tools/",
  },
  {
    icon: "✨",
    show: true,
    id: "a0raEOBHGPVl3a",
    title: t("tools.bmi.title"),
    description: t("tools.bmi.description"),
    path: "bmi-calculator",
    pathname: "/tools/",
  },
  {
    icon: "💸",
    show: true,
    id: "duk6K3jJwOr28h",
    title: t("tools.currency_converter.short_title"),
    description: t("tools.currency_converter.description"),
    path: "currency-converter",
    pathname: "/tools/",
  },
  {
    icon: "🗝️",
    show: true,
    id: "iOepl4QqFOgXDz",
    title: t("tools.id_generator.short_title"),
    description: t("tools.id_generator.description"),
    path: "id-generator",
    pathname: "/tools/",
  },
];
