// Objeto con tasas de cambio y configuración de monedas
export const exchangeRates = {
  BTC: {
    show: !true,
    symbol: "₿",
    rate: 0.0000083,
    decimal: 4,
    code: "BTC",
    label: "BTC — Bitcoin",
    title: "Bitcoin",
  },
  SVC: {
    show: !true,
    symbol: "₡",
    rate: 8.75,
    decimal: 2,
    code: "SVC",
    label: "SVC — Colón salvadoreño",
    title: "Colón salvadoreño",
  },
  AUD: {
    show: !true,
    symbol: "$",
    rate: 1.534,
    decimal: 2,
    code: "AUD",
    label: "AUD — Dólar australiano",
    title: "Dólar australiano",
  },
  USD: {
    show: true,
    symbol: "$",
    rate: 1,
    decimal: 2,
    code: "USD",
    label: "USD — Dólar estadounidense",
    title: "Dólar estadounidense",
  },
  ETH: {
    show: !true,
    symbol: "Ξ",
    rate: 0.00023,
    decimal: 3,
    code: "ETH",
    label: "ETH — Ethereum",
    title: "Ethereum",
  },
  EUR: {
    show: true,
    symbol: "€",
    rate: 0.8604,
    decimal: 2,
    code: "EUR",
    label: "EUR — Euro",
    title: "Euro",
  },
  GBP: {
    show: !true,
    symbol: "",
    rate: 0.7443,
    decimal: 2,
    code: "GBP",
    label: "GBP — Libra esterlina",
    title: "Libra esterlina",
  },
  MXN: {
    show: !true,
    symbol: "$",
    rate: 18.68,
    decimal: 2,
    code: "MXN",
    label: "MXN — Peso mexicano",
    title: "Peso mexicano",
  },
};
